# Generated by Django 4.1.3 on 2022-11-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_title', models.CharField(max_length=50)),
                ('p_content0', models.CharField(default='', max_length=200)),
                ('p_heading', models.CharField(default='', max_length=100)),
                ('p_content1', models.CharField(default='', max_length=500)),
                ('p_subhead0', models.CharField(default='', max_length=100)),
                ('p_content2', models.CharField(default='', max_length=500)),
                ('p_subhead1', models.CharField(default='', max_length=100)),
                ('p_content3', models.CharField(default='', max_length=500)),
                ('p_thumb', models.ImageField(default='', upload_to='static/images')),
            ],
        ),
    ]
